---
kind: pipeline
name: tests

steps:
- name: lint
  image: miki725/pre-commit

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: deploy

steps:
- name: deploy
  image: docker/compose:1.24.1
  environment:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: /tmp/docker-certs
    DOCKER_MACHINE_NAME: firstrussianny
    COMPOSE_PROJECT_NAME: sda-api
    DJANGO_SITE_URL:
      from_secret: DJANGO_SITE_URL
    DJANGO_DATABASE_URL:
      from_secret: DJANGO_DATABASE_URL
    DJANGO_SECRET_KEY:
      from_secret: DJANGO_SECRET_KEY
    POSTGRES_DB:
      from_secret: POSTGRES_DB
    POSTGRES_PASSWORD:
      from_secret: POSTGRES_PASSWORD
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    DOCKER_HOST:
      from_secret: DOCKER_HOST
    DOCKER_CA_CERT:
      from_secret: DOCKER_CA_CERT
    DOCKER_CLIENT_CERT:
      from_secret: DOCKER_CLIENT_CERT
    DOCKER_CLIENT_KEY:
      from_secret: DOCKER_CLIENT_KEY
    CERTBOT_EMAIL:
      from_secret: CERTBOT_EMAIL
    PGDATA_VOLUME: /var/lib/docker-volumes/firstrussianny/pgdata
    MEDIA_VOLUME: /var/lib/docker-volumes/firstrussianny/media
    APP_PUBLIC_PORT: 172.17.0.1:8000
  commands:
    - mkdir -p $DOCKER_CERT_PATH
    - printenv DOCKER_CA_CERT > $DOCKER_CERT_PATH/ca.pem
    - printenv DOCKER_CLIENT_CERT > $DOCKER_CERT_PATH/cert.pem
    - printenv DOCKER_CLIENT_KEY > $DOCKER_CERT_PATH/key.pem
    - |
      docker-compose run --rm \
          certbot certificates \
        2>&1 \
        | grep "No certs found" \
        && docker-compose run --rm \
          -p 80:80 \
          certbot certonly \
            --non-interactive \
            --agree-tos \
            -m $CERTBOT_EMAIL \
            --standalone \
            --must-staple \
            -d firstrussiansda.org \
            -d www.firstrussiansda.org \
            -d api.firstrussiansda.org \
        || true
    - docker-compose build --pull
    - docker-compose up certbot
    - docker-compose up -d
    # load renewed certs
    - docker-compose kill -s HUP nginx || true
    - timeout -t 10 docker-compose logs -f app nginx || true

trigger:
  ref:
    - refs/heads/master

---
kind: pipeline
name: backup

steps:
- name: backup
  image: docker/compose:1.24.1
  environment:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: /tmp/docker-certs
    DOCKER_MACHINE_NAME: firstrussianny
    COMPOSE_PROJECT_NAME: sda-api
    POSTGRES_DB:
      from_secret: POSTGRES_DB
    POSTGRES_PASSWORD:
      from_secret: POSTGRES_PASSWORD
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    DOCKER_HOST:
      from_secret: DOCKER_HOST
    DOCKER_CA_CERT:
      from_secret: DOCKER_CA_CERT
    DOCKER_CLIENT_CERT:
      from_secret: DOCKER_CLIENT_CERT
    DOCKER_CLIENT_KEY:
      from_secret: DOCKER_CLIENT_KEY
    CERTBOT_EMAIL:
      from_secret: CERTBOT_EMAIL
  commands:
    - mkdir -p $DOCKER_CERT_PATH
    - printenv DOCKER_CA_CERT > $DOCKER_CERT_PATH/ca.pem
    - printenv DOCKER_CLIENT_CERT > $DOCKER_CERT_PATH/cert.pem
    - printenv DOCKER_CLIENT_KEY > $DOCKER_CERT_PATH/key.pem
    - |
      docker-compose run --rm \
        -e "PGUSER=$POSTGRES_USER" \
        -e "PGPASSWORD=$POSTGRES_PASSWORD" \
        -e "PGDATABASE=$POSTGRES_DB" \
        -v "/var/lib/docker-volumes/firstrussianny/backup:/backup" \
        db \
        pg_dump \
          -h db \
          --data-only \
          --file=/backup/$(date -u +"%Y-%m-%dT%H-%M-%SZ").sql

trigger:
  event:
    - cron
  cron:
    - hourly

---
kind: secret
name: DJANGO_SITE_URL
get:
  path: drone/data/firstrussianny/SDA-API
  name: DJANGO_SITE_URL

---
kind: secret
name: DJANGO_DATABASE_URL
get:
  path: drone/data/firstrussianny/SDA-API
  name: DJANGO_DATABASE_URL

---
kind: secret
name: DJANGO_SECRET_KEY
get:
  path: drone/data/firstrussianny/SDA-API
  name: DJANGO_SECRET_KEY

---
kind: secret
name: POSTGRES_DB
get:
  path: drone/data/firstrussianny/SDA-API
  name: POSTGRES_DB

---
kind: secret
name: POSTGRES_PASSWORD
get:
  path: drone/data/firstrussianny/SDA-API
  name: POSTGRES_PASSWORD

---
kind: secret
name: POSTGRES_USER
get:
  path: drone/data/firstrussianny/SDA-API
  name: POSTGRES_USER

---
kind: secret
name: DOCKER_HOST
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_HOST

---
kind: secret
name: DOCKER_CA_CERT
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CA_CERT

---
kind: secret
name: DOCKER_CLIENT_CERT
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CLIENT_CERT

---
kind: secret
name: DOCKER_CLIENT_KEY
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CLIENT_KEY

---
kind: secret
name: CERTBOT_EMAIL
get:
  path: drone/data/firstrussianny/SDA-API
  name: CERTBOT_EMAIL

---
kind: signature
hmac: b500807c852b27b71e4be587e7bcf2363018d5ce654912f5b2e5403df0080d4a

...
