version: "3.7"

networks:
  app: {}

volumes:
  pgdata:
  media:

services:
  db:
    image: postgres:12-alpine
    env_file: ${ENV_FILE:-envs/prod.env}
    networks:
      - app
    volumes:
      - ${PGDATA_VOLUME:-pgdata}:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIPENV_FLAGS: ${PIPENV_FLAGS:---deploy --system}
    init: true
    env_file:
      - envs/base.env
      - ${ENV_FILE:-envs/prod.env}
    depends_on:
      - db
    networks:
      - app
    ports:
      - 8000:8000
    volumes:
      - $PWD:${MOUNT_PATH:-/tmp}
      - ${MEDIA_VOLUME:-media}:/media
