version: "3.7"

networks:
  app: {}

volumes:
  pgdata:
  data:
  media:
  certs:

services:
  db:
    image: postgres:12-alpine
    env_file: ${ENV_FILE:-envs/prod.env}
    networks:
      - app
    volumes:
      - ${PGDATA_VOLUME:-pgdata}:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIPENV_FLAGS: ${PIPENV_FLAGS:---deploy --system}
    init: true
    env_file:
      - envs/base.env
      - ${ENV_FILE:-envs/prod.env}
    depends_on:
      - db
    networks:
      - app
    ports:
      - ${APP_PUBLIC_PORT:-8000}:8000
    volumes:
      - $PWD:${MOUNT_PATH:-/tmp}
      - data:/data
      - ${MEDIA_VOLUME:-media}:/media
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - data:/data
      - ${MEDIA_VOLUME:-media}:/media
      - certs:/etc/letsencrypt
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    networks:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    command: renew --must-staple --webroot --webroot-path=/data -v
    volumes:
      - data:/data
      - ${MEDIA_VOLUME:-media}:/media
      - certs:/etc/letsencrypt
